### ISSUE TITLE
Не работает плагин WooCommerce Checkout Field Editor при установленном wc-edostavka

### ISSUE THREAD

**Issue by modestie** [kalbac/wc-edostavka#32]
Подскажите как исправить ошибку? При установленном плагине wc-edostavka плагин WooCommerce Checkout Field Editor выдает следующую ошибку:

Fatal error: Uncaught Error: Call to a member function get() on null in /home/s/sandfantas/shop_www/public_html/wp-content/plugins/wc-edostavka-1.4.0/includes/functions.php:11 Stack trace: #0 /home/s/sandfantas/shop_www/public_html/wp-content/plugins/wc-edostavka-1.4.0/wc-edostavka.php(233): wc_edostavka_get_chosen_shipping_method() #1 /home/s/sandfantas/shop_www/public_html/wp-includes/class-wp-hook.php(298): WC_Edostavka_Shipping->default_address_fields(Array) #2 /home/s/sandfantas/shop_www/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 /home/s/sandfantas/shop_www/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(607): apply_filters('woocommerce_def...', Array) #4 /home/s/sandfantas/shop_www/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(997): WC_Countries->get_default_address_fields() #5 /home/s/sandfantas/shop_www/public_html/wp-content/plugins/woocommerce-checkout-field-editor/classes/class-wc-checkout-field-editor.php(166): WC_Cou in /home/s/sandfantas/shop_www/public_html/wp-content/plugins/wc-edostavka-1.4.0/includes/functions.php on line 11

**Comment by vguns** [comment]
Тоже конфликтует с этим плагином
